AB#3538536 [WHATSAPP-BOT] - Perf/send file
develupo/venom pull request #109
Opened 2024-07-30 18:35 UTC by GabrielBdeC

Fixes # .

## Changes proposed in this pull request

-
-

To test (it takes a while): `npm install github:<username>/venom#<branch>`

2024-07-31 14:19 UTC, CBeraldo requested changes

2024-07-31 14:19 UTC, CBeraldo commented on src/api/layers/sender.layer.ts
> +    }
Acho que essa parte toda aqui da duplicada em todos os cenários. Poderia unificar.

2024-07-31 14:19 UTC, CBeraldo commented on src/api/layers/sender.layer.ts
> +      if (error.message.includes('protocolTimeout')) {
Essa validação já estava sendo feita ou foi adicionada?

2024-07-31 14:45 UTC, GabrielBdeC-TR commented on src/api/layers/sender.layer.ts
> +      if (error.message.includes('protocolTimeout')) {
Já existia

2024-08-01 13:31 UTC, CBeraldo approved these changes

2024-08-01 13:31 UTC, merged