AB#3501489 [WHATSAPP-BOT] - Perf/inject
develupo/venom pull request #149
Opened 2024-10-14 18:41 UTC by GabrielBdeC

Fixes # .

## Changes proposed in this pull request

-
-

To test (it takes a while): `npm install github:<username>/venom#<branch>`

2024-10-15 17:15 UTC, CBeraldo requested changes

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/store/type-attribute-from-protobuf.inject.js
> +  return 'text'
Função não faz sentido.

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/wapi.js
> +  getStore().catch()
Motivo?

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/wapi.js
> +        setTimeout(checkObjects, 100)
Pra que serve?

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/store/media-type-from-protobuf.inject.js
> +  const [proto] = args
Pra que serve?

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/store/create-msg-protobuf.inject.js
> +  const proto = oldFunction(...args)
Pra que serve?

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/store/create-fanout-msg-stanza.inject.js
> +  const [, proto] = args
Pra que serve?

2024-10-15 17:15 UTC, CBeraldo commented on src/lib/wapi/functions/add-chat-wapi.js
> +  window.Store.Vcard = self.importNamespace('WAWebFrontendVcardUtils')
São só esses módulos? Lembro que tinha mais coisa no map da store object.

2024-10-15 20:05 UTC, CBeraldo requested changes

2024-10-15 20:05 UTC, CBeraldo commented on src/lib/wapi/store/get-store.js
function customImportNamespace(namespace, property) {
   try {
      const importNamespace = self.importNamespace(namespace)
      return property ? importNamespace[property] : importNamespace
   } catch (error) {
      console.error(error)
   }
}

window.Store.UserConstructor = customImportNamespace('WAWebWid', 'default')

OU 

function customImportNamespace(namespace) {
   try {
      return self.importNamespace(namespace)
   } catch (error) {
      console.error(error)
   }
}

window.Store.UserConstructor = customImportNamespace('WAWebWid')?.default

2024-10-15 20:05 UTC, CBeraldo commented on src/lib/wapi/store/type-attribute-from-protobuf.inject.js
> +  return 'text'
Verifica se faz algo, se não fizer remove.

2024-10-15 20:05 UTC, CBeraldo commented on src/lib/wapi/functions/add-chat-wapi.js
> +  window.Store.MaybeMeUser = self.importNamespace('WAWebUserPrefsMeUser')
Ajustar da mesma forma que o wapi.js o self.importNamespace.

2024-10-16 12:57 UTC, GabrielBdeC commented on src/lib/wapi/wapi.js
> +        setTimeout(checkObjects, 100)
Copilot, GPT 4o e llama, todos retornaram:


![image](https://github.com/user-attachments/assets/badbd268-8a6e-41a3-ba46-803d584eb369)


Adiciona um while e um promise, não sei se faria sentido

2024-10-16 13:09 UTC, GabrielBdeC commented on src/lib/wapi/wapi.js
>    return new Promise((resolve) => {
Não vejo como evitar esse caso, já que a necessidade desse new promise é justamente pra trancar a função até carregar o outro processo.

Em etapas futuras, a ideia é remover esse cara e adicionar de forma lazy e com eventos, o que vai ser bem melhor que é atualmente.

2024-10-16 14:49 UTC, CBeraldo requested changes

2024-10-16 14:49 UTC, CBeraldo commented on src/lib/wapi/store/get-store.js
> +  window.Store.MsgKey = customImportNamespace('WAWebMsgKey').default
?.default

2024-10-16 14:49 UTC, CBeraldo commented on src/lib/wapi/store/get-store.js
> +  window.Store.UploadUtils = customImportNamespace('WAWebUploadManager').default
?.default

2024-10-16 14:49 UTC, CBeraldo commented on src/lib/wapi/store/get-store.js
> +  ).default
?.default

2024-10-16 14:49 UTC, CBeraldo commented on src/lib/wapi/store/get-store.js
> +    window[inject.id] = self.importNamespace(inject.module)
customImportNamespace?
Acho que é bom colocar umas tratativas aqui e uns logs de erro pra caso o window[inject.id] ou module seja undefined.

2024-10-16 17:40 UTC, CBeraldo approved these changes

2024-10-16 17:41 UTC, CBeraldo approved these changes

2024-10-16 17:41 UTC, merged