Fix/init qr
develupo/venom pull request #17
Opened 2024-04-12 10:27 UTC by GabrielBdeC

Fixes # .

## Changes proposed in this pull request

-
-

To test (it takes a while): `npm install github:<username>/venom#<branch>`

2024-04-12 13:32 UTC, CBeraldo requested changes

2024-04-12 13:32 UTC, CBeraldo commented on src/api/layers/host.layer.ts
> +        if (error.message === 'Creation Stopped') {
logger.error

2024-04-12 13:32 UTC, CBeraldo commented on src/api/layers/listener.layer.ts
> +  private callOnack = new callbackWile()
add comentário de refact para esse callbackWile

2024-04-12 13:32 UTC, CBeraldo commented on src/controllers/status.ts
> +import { Status, StatusFind } from './initializer'
Trazer dados de status para ca.

2024-04-12 13:32 UTC, CBeraldo commented on src/controllers/status.ts
> +const statusSession: StatusSession = {}
Refactor para o estilo do instance do venom utilizando class.

class StatusManagement {
    statusSession: StatusSession = {}

   ...
}

export const statusSessionManangemetn = new StatusMan().

2024-04-12 13:35 UTC, CBeraldo requested changes

2024-04-12 13:35 UTC, CBeraldo commented on src/controllers/initializer.ts
>        statusFind('connectBrowserWs', session)
onStatusCallback

2024-04-12 13:35 UTC, CBeraldo commented on src/controllers/initializer.ts
>        statusFind('connectBrowserWs', session)
Trazer para dentro do statusManagemnt

2024-04-16 13:30 UTC, CBeraldo requested changes

2024-04-16 13:30 UTC, CBeraldo commented on src/controllers/initializer.ts
> +        let isLogged: boolean
Verificar necessidade do try/catch. Poderia utilizar o próprio !isLogged para dar o client.close.

2024-04-16 13:30 UTC, CBeraldo commented on src/controllers/initializer.ts
> +                waitLoginPromise = client.waitForLogin(catchQR)
Testar e verificar necessidade do client.close.

2024-04-16 17:07 UTC, GabrielBdeC commented on src/controllers/initializer.ts
> +        let isLogged: boolean
Coloquei para identificar a mensagem de erro no catch para retorno no reject, já que se fosse boolean, só teria uma informação e não saberíamos o que originou (além dos logs) o erro

2024-04-16 17:08 UTC, GabrielBdeC commented on src/controllers/initializer.ts
> +                waitLoginPromise = client.waitForLogin(catchQR)
Não pode existir, essa parte é responsável pelo reconnect do QRCode.

Por conta dela, nós conseguimos receber o QRCode. Caso algo dê errado (próprio wpp quebra às vezes), ela fecharia o processo e não permitiria retentativa.

Isso é diferente da inicialização da instância, q é algo mais importante de ter iniciado corretamente

2024-04-17 14:53 UTC, merged