Fixing group errors when phoneNumber has the 9 digit
develupo/venom pull request #51
Opened 2024-05-06 19:00 UTC by fernanda-di-queiroz-f

Fixes # .

## Changes proposed in this pull request

- Fixing result formatting error when phoneNumber has the 9 digit 

To test (it takes a while): `npm install github:<username>/venom#<branch>`

2024-05-06 19:19 UTC, CBeraldo requested changes

2024-05-06 19:19 UTC, CBeraldo commented on src/lib/wapi/validation/group.js
> +export const normalizePhoneNumber = (phoneNumber) => {
Basear no whatsapp-server temos esse mesmo problema.

2024-05-07 13:46 UTC, fernanda-di-queiroz-f commented on src/lib/wapi/validation/group.js
> +export const normalizePhoneNumber = (phoneNumber) => {
Ajustado

2024-05-07 15:35 UTC, CBeraldo requested changes

2024-05-07 15:35 UTC, CBeraldo commented on src/lib/wapi/validation/group.js
> +export const normalizePhoneNumber = (contactPhoneNumber) => {
Criar novo arquivo

2024-05-07 15:35 UTC, CBeraldo commented on src/lib/wapi/functions/remove-participant.js
>      const phoneNumber = participant.userWid._serialized
const index = getContactIndex(phoneNumber, contacts)

2024-05-07 19:59 UTC, merged