feat: add html cached version
develupo/venom pull request #63
Opened 2024-05-21 13:06 UTC by GabrielBdeC

Fixes # .

## Changes proposed in this pull request

-
-

To test (it takes a while): `npm install github:<username>/venom#<branch>`

2024-05-21 16:55 UTC, CBeraldo requested changes

2024-05-21 16:55 UTC, CBeraldo commented on src/api/whatsapp.ts
> +        this.options.webVersion &&
Confirmar force webpack false/true

2024-05-21 16:55 UTC, CBeraldo commented on src/controllers/browser.ts
> +    if (
whatsappCacheManager/service
 ! return null
this.existsWAVErsionHTML
this.existsWAVErsion

2024-05-27 13:51 UTC, vinnydeveloper requested changes

2024-05-27 13:51 UTC, vinnydeveloper commented on src/controllers/browser.ts
> +  whatsappCacheManagement.setup(waPage, options)
Colocar dentro do trycatch

```suggestion
  whatsappCacheManagement.setup(waPage, options)
```

2024-05-27 13:51 UTC, vinnydeveloper commented on src/controllers/whatsapp-cache-management.ts
> +  async setup(waPage: Page, options: options | CreateConfig) {
Não é necessário o async

```suggestion
  async setup(waPage: Page, options: options | CreateConfig) {
```

2024-05-28 16:40 UTC, vinnydeveloper approved these changes

2024-05-28 16:42 UTC, merged